name: policy-meta-operator
serviceType: managed

image:
  registry: gsoci.azurecr.io
  name: giantswarm/policy-meta-operator
  tag: v0.0.1
  pullPolicy: IfNotPresent

edgedb:
  host: edgedb
  port: 5656
  user: edgedb
  passwordSecret:
    name: edgedb-serverpassword
  tlsSecret:
    name: edgedb-server-tls
