apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: {{ default "1" .Values.replicas }}
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      labels:
        {{- include "labels.common" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  {{- include "labels.selector" . | nindent 18 }}
              topologyKey: kubernetes.io/hostname
            weight: 100
      serviceAccountName: {{ include "resource.default.name"  . }}
      securityContext:
        {{- with .Values.podSecurityContext }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
      {{- with .Values.imagePullSecrets }}
        imagePullSecrets:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: edgedb-tls
          secret:
            secretName: {{ .Values.edgedb.tlsSecret.name }}
      containers:
      - name: {{ include "resource.default.name" . }}
        image: "{{ default .Values.image.registry (include "global.imageRegistry" . ) }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.Version }}"
        env:
        - name: EDGEDB_HOST
          value: {{ .Values.edgedb.host | quote }}
        - name: EDGEDB_PORT
          value: {{ .Values.edgedb.port | quote }}
        - name: EDGEDB_USER
          value: {{ .Values.edgedb.user | quote }}
        - name: EDGEDB_PASSWORD
          valueFrom:
           secretKeyRef:
              name: {{ .Values.edgedb.passwordSecret.name }}
              key: password
        - name: EDGEDB_TLS_CA_FILE
          value: "/etc/edgedb/tls-ca.crt"
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- with .Values.containerSecurityContext }}
        securityContext:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: edgedb-tls
          readOnly: true
          mountPath: "/etc/edgedb/tls-ca.crt"
