apiVersion: policy.giantswarm.io/v1alpha1
kind: Policy
metadata:
  name: disallow-privileged-containers
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  defaultPolicyState: "enforce"
